name: App_CICD_Setup

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 자동 배포가 동작합니다.

jobs:
  BuildImage-And-PushDockerhub:
    runs-on: ubuntu-latest
    steps:
      # 1. 깃허브 저장소의 코드를 가상 빌드 환경(Runner)에 복사
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 빌드에 필요한 JDK 21 환경 세팅
      - name: Setup JRE
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "zulu"

      # 3. 스프링 부트 빌드 실행 (실제 폴더명인 backEnd/app 으로 이동하여 빌드)
      - name: Build with bootJar
        run: |
          cd backEnd/app
          chmod +x ./gradlew
          ./gradlew clean bootJar

      # 4. 도커 이미지 빌드 (저장소 명을 petandifor 로 설정)
      - name: Build Docker Image with Dockerfile
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_ID }}/petandifor:latest ./

      # 5. 도커 허브 로그인 (깃허브 Secret 정보 사용)
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      # 6. 도커 허브 원격 저장소로 이미지 업로드(Push)
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_ID }}/petandifor:latest

  Build-And-Deploy:
    needs: BuildImage-And-PushDockerhub
    runs-on: ubuntu-latest
    steps:
      # 7. EC2 서버에 SSH 원격 접속 후 도커 컨테이너 교체 배포 실행
      - name: executing remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_KEY }}
          username: ubuntu
          port: 22
          script: |
            # 1) 기존 실행 중인 petandifor-container 컨테이너가 있다면 강제 종료 및 삭제
            sudo docker rm -f petandifor-container || true

            # 2) 서버에 캐시되어 있는 기존 버전의 도커 이미지 삭제
            sudo docker rmi -f ${{ secrets.DOCKER_HUB_ID }}/petandifor:latest || true

            # 3) 도커 허브에서 새 이미지를 pull 받아 컨테이너 구동
            # (ALB 로드밸런서에서 EC2의 80포트로 넘겨주고, 컨테이너 내부의 80포트로 연결하므로 -p 80:80 설정)
            sudo docker run -d --name petandifor-container -p 80:80 ${{ secrets.DOCKER_HUB_ID }}/petandifor:latest
